# Generated by Django 4.2.5 on 2023-09-28 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0005_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
