# Generated by Django 4.2.5 on 2023-10-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0009_alter_profile_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='profile',
            name='image2',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=''),
        ),
    ]
