# Generated by Django 4.2.5 on 2023-10-12 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0010_rename_image_profile_image1_profile_image2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image2',
            new_name='banner',
        ),
    ]
