# Generated by Django 4.2.3 on 2023-12-08 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0012_alter_post_image_alter_profile_banner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
